spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hotel?useSSL=true
      username: root
      password: root
  servlet:
     multipart:  
        max-file-size: 2097152
        max-request-size: 10485760    
mybatis:
  config-location: classpath:mybatis2.xml